version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: sh -c "poetry install --no-root --no-interaction --no-ansi && poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"